import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { AnalyticsStore } from '../../../stores/analytics.store';
import { Histogram } from '../../../ui/histogram';
import { Panel } from '../../../ui/layout';
import { LineChart, LineChartSeries } from '../../../ui/line-chart';
import { PanelHeader } from '../../../ui/panel-header';
import { MultiplePane, SmallMultiples } from '../../../ui/small-multiples';

/** Scoped edge monitoring above all-time validation evidence. */
@Component({selector:'sb-edge-tab',changeDetection:ChangeDetectionStrategy.OnPush,imports:[Panel,PanelHeader,LineChart,SmallMultiples,Histogram],template:`<div class="panels"><sb-panel><sb-panel-header title="Rolling win rate" [n]="store.scopeN()"/><sb-line-chart [series]="rollingWr()" [referenceLine]="performance()?.win_rate ?? null" [valueFormat]="pct"/></sb-panel><sb-panel><sb-panel-header title="Rolling ExpR" [n]="store.scopeN()"/><sb-line-chart [series]="rollingExpR()" [referenceLine]="0" [valueFormat]="r"/></sb-panel><sb-panel><sb-panel-header title="Strategy cumulative R" [n]="store.scopeN()"/><sb-small-multiples [panes]="strategyPanes()" [valueFormat]="r"/></sb-panel><sb-panel><sb-panel-header title="Calibration deciles" allTime/><sb-histogram [bins]="decileBins()"/></sb-panel></div>`,styles:`.panels{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-14)}@media(max-width:800px){.panels{grid-template-columns:1fr}}`})
export class EdgeTab { readonly store=inject(AnalyticsStore); readonly performance=computed(()=>this.store.performance()); readonly pct=(v:number)=>`${v.toFixed(1)}%`;readonly r=(v:number)=>`${v.toFixed(2)}R`; readonly rollingWr=computed<LineChartSeries[]>(()=>[{name:'Win rate',points:(this.performance()?.rolling_wr??[]).map(x=>({date:x.date,value:x.win_rate}))}]);readonly rollingExpR=computed<LineChartSeries[]>(()=>[{name:'ExpR',points:(this.performance()?.rolling_exp_r??[]).map(x=>({date:x.date,value:x.exp_r}))}]);readonly strategyPanes=computed<MultiplePane[]>(()=>Object.entries(this.store.strategies()?.cumulative??{}).map(([title,rows])=>({title,series:[{name:title,points:rows.map(x=>({date:x.date,value:x.cum_r}))]})));readonly decileBins=computed(()=>((this.store.calibration()?.deciles??[]) as {decile:string;win_rate:number|null}[]).filter(x=>x.win_rate!==null).map(x=>({label:x.decile,count:x.win_rate!})));}
