"""Loader for the committed out-of-sample validation registry.

The JSON is GENERATED by scripts/backtest/run_backtest_range.py --emit-registry;
hand-edits are forbidden except the initial round-1 seed
(docs/superpowers/results/2026-07-validation.md). That generator refuses to
write a row for an unhealthy run (see its REFUSAL_TOKENS) -- a missing cell is
a refusal to be re-run, not a gap to be filled in by hand.

Rows carry a run_date but no age. `decay_for` derives one at READ TIME --
fresh / aging / stale / unknown -- and `decay_note` renders it. The verdict is
never written back: it would be wrong the day after it was stored. It also
gates nothing; see docs/claude/backtest-methodology.md.
"""
from __future__ import annotations

import datetime as dt
import json
from dataclasses import dataclass
from pathlib import Path

_PATH = Path(__file__).with_name("validation_registry.json")
_CACHE: list | None = None

# One and two missed quarterly re-verification cycles. They are not round
# numbers picked for feel: evidence is re-derived quarterly, so a row that has
# survived one missed cycle is `aging` and one that has survived two is
# `stale`. Do not "tune" these without changing that cadence first.
DECAY_AGING_DAYS: int = 90
DECAY_STALE_DAYS: int = 180


def decay_for(run_date: str | None, today: dt.date | None = None) -> str:
    """Read-time staleness verdict for a registry row's run_date.

    Returns "fresh" | "aging" | "stale" | "unknown". NEVER persisted -- a
    stored verdict is wrong the day after it is written. Boundaries belong to
    the stricter side (age >= 180 is stale, age >= 90 is aging), and an
    unusable or missing run_date is "unknown" rather than "fresh": an
    unstamped legacy row is not evidence of freshness.

    This verdict does not gate anything. No plan is refused, no alert
    suppressed and no badge downgraded because a row is stale -- excluding
    stale evidence would change which plans get built, which needs its own
    pre-registered hypothesis.
    """
    if not isinstance(run_date, str) or not run_date:
        return "unknown"
    try:
        stamped = dt.date.fromisoformat(run_date.strip())
    except ValueError:
        return "unknown"
    age = ((today or dt.date.today()) - stamped).days
    if age >= DECAY_STALE_DAYS:
        return "stale"
    if age >= DECAY_AGING_DAYS:
        return "aging"
    return "fresh"


# The one rendering of a decay verdict, shared by every badge surface so they
# cannot drift apart. "fresh" is silent (no news is not news); "unknown" is
# neutral, NOT a warning -- an unstamped legacy row is not a stale one.
_DECAY_NOTES = {
    "fresh": "",
    "aging": f" · evidence aging ({DECAY_AGING_DAYS}d+)",
    "stale": f" · evidence stale ({DECAY_STALE_DAYS}d+)",
    "unknown": " · evidence undated",
}


def decay_note(decay: str) -> str:
    """Display suffix for a decay verdict. Display only -- it gates nothing."""
    return _DECAY_NOTES.get(decay, _DECAY_NOTES["unknown"])


@dataclass
class Badge:
    status: str          # "VALIDATED" | "WEAK"
    n: int
    win_rate: float
    expectancy_r: float
    window: str = ""
    run_date: str = ""
    decay: str = "unknown"   # derived at read time by decay_for; never persisted


def load_registry(path: Path | None = None) -> list:
    global _CACHE
    if _CACHE is None or path is not None:
        _CACHE = json.loads((path or _PATH).read_text(encoding="utf-8"))
    return _CACHE


def reload_registry() -> None:
    global _CACHE
    _CACHE = None


def get_badge(source: str, strategy: str, horizon_key: str | None = None) -> Badge:
    """Most-specific match: exact horizon record, else pooled (horizon null),
    else a default WEAK badge with zero sample.

    Every live scan-loop plan is attributed source="confluence" (see
    build_confluence_plan), but the registry only ever records confluence
    rows pooled under the literal strategy "ALL" -- the per-strategy
    VALIDATED rows (RSI, Fibonacci, MACD, ...) all live under
    source="strategy", a path the live scan loop never calls. Matching
    source+strategy+horizon exactly therefore missed on every real plan and
    fell straight through to a hardcoded WEAK/n=0 badge, regardless of how
    well-validated that plan's primary confirming method actually was.
    `strategy` here is already the plan's real primary confirming method
    (see primary_strategy_for), so before giving up, check whether that
    same strategy was independently OOS-validated on its own signal path --
    that's real evidence about this plan too, not a coincidence."""
    records = load_registry()

    def _find(src, strat, hz):
        for r in records:
            if r["source"] == src and r["strategy"] == strat and r.get("horizon") == hz:
                return r
        return None

    rec = (_find(source, strategy, horizon_key)
           or _find(source, strategy, None)
           or (source == "confluence" and (
               _find("strategy", strategy, horizon_key)
               or _find("strategy", strategy, None)))
           or _find(source, "ALL", horizon_key)
           or _find(source, "ALL", None))
    if rec is None:
        return Badge(status="WEAK", n=0, win_rate=0.0, expectancy_r=0.0)
    run_date = rec.get("run_date", "")
    return Badge(status=rec["status"], n=rec["n"], win_rate=rec["win_rate"],
                 expectancy_r=rec["expectancy_r"], window=rec.get("window", ""),
                 run_date=run_date, decay=decay_for(run_date))
