"""Loader for the committed out-of-sample validation registry.

The JSON is GENERATED by scripts/run_backtest_range.py --emit-registry;
hand-edits are forbidden except the initial round-1 seed
(docs/superpowers/results/2026-07-validation.md).
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

_PATH = Path(__file__).with_name("validation_registry.json")
_CACHE: list | None = None


@dataclass
class Badge:
    status: str          # "VALIDATED" | "WEAK"
    n: int
    win_rate: float
    expectancy_r: float
    window: str = ""
    run_date: str = ""


def load_registry(path: Path | None = None) -> list:
    global _CACHE
    if _CACHE is None or path is not None:
        _CACHE = json.loads((path or _PATH).read_text(encoding="utf-8"))
    return _CACHE


def reload_registry() -> None:
    global _CACHE
    _CACHE = None


def get_badge(source: str, strategy: str, horizon_key: str | None = None) -> Badge:
    """Most-specific match: exact horizon record, else pooled (horizon null),
    else a default WEAK badge with zero sample."""
    records = load_registry()

    def _find(hz):
        for r in records:
            if r["source"] == source and r["strategy"] == strategy and r.get("horizon") == hz:
                return r
        return None

    rec = _find(horizon_key) or _find(None)
    if rec is None:
        return Badge(status="WEAK", n=0, win_rate=0.0, expectancy_r=0.0)
    return Badge(status=rec["status"], n=rec["n"], win_rate=rec["win_rate"],
                 expectancy_r=rec["expectancy_r"], window=rec.get("window", ""),
                 run_date=rec.get("run_date", ""))
