"""Synthetic OHLCV builder with per-bar High/Low control.

Complements conftest.make_ohlcv (float-only, spread-derived High/Low):
this variant accepts (open, high, low, close) tuples so exit-model tests
can place highs/lows exactly on stop/target/trigger levels.
"""
import pandas as pd


def make_ohlcv(closes, *, start="2024-01-02", spread=0.01, volume=1_000_000):
    """Build a daily OHLCV frame from floats or (open, high, low, close) tuples."""
    rows = []
    for c in closes:
        if isinstance(c, (tuple, list)):
            o, h, l, cl = (float(x) for x in c)
        else:
            o = cl = float(c)
            h, l = cl * (1 + spread), cl * (1 - spread)
        rows.append((o, h, l, cl, float(volume)))
    idx = pd.bdate_range(start=start, periods=len(rows))
    return pd.DataFrame(rows, columns=["Open", "High", "Low", "Close", "Volume"], index=idx)


def registry_strategy_row(status: str) -> dict:
    """First source="strategy" row in the committed registry with `status`.

    Badge tests take their exemplar from the registry rather than naming a
    strategy. The file is regenerated by `--emit-registry`, and an honest
    re-emission (f10c4fe2 demoted Fibonacci and RSI) broke every test that
    pinned one strategy's old numbers. What these tests guard is that a row's
    numbers reach each badge surface intact, not which strategy holds which
    badge this quarter.
    """
    from swingbot.core.backtesting.registry import load_registry

    rows = [r for r in load_registry()
            if r["source"] == "strategy" and r["status"] == status]
    assert rows, f"committed registry has no {status} strategy row to exercise"
    return rows[0]
