import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { CHART_CHROME } from './chart/chart-frame';
import { ABSENT } from './format';

export interface BarRow { label: string; value: number | null; n?: number | null; withheld?: boolean; }
export type BarListMode = 'signed' | 'rate';
type Tone = 'pos' | 'neg' | 'above' | 'below';
interface Drawn extends BarRow { text: string; left: number; width: number; tone: Tone; }

@Component({selector:'sb-bar-list',changeDetection:ChangeDetectionStrategy.OnPush,template:`<ul>@for(row of drawn();track row.label){<li [class.withheld]="row.withheld"><span class="label" [title]="row.label">{{row.label}}</span><span class="track" aria-hidden="true">@if(mode()==='signed'){<span class="axis"></span>}@if(mode()==='rate'&&reference()!==null){<span class="ref" [style.left.%]="clamp(reference()!)"></span>}@if(row.width>0){<span class="fill" [attr.data-tone]="row.tone" [style.left.%]="row.left" [style.width.%]="row.width"></span>}</span><span class="value num">{{row.text}}</span><span class="n num">{{nText(row)}}</span></li>}</ul>`,styles:`:host{display:block}ul{display:grid;gap:var(--space-4);margin:0;padding:0;list-style:none}li{display:grid;grid-template-columns:9rem minmax(0,1fr) 5rem 4.5rem;align-items:center;gap:var(--space-8);font-size:var(--text-table)}@media(max-width:639px){li{grid-template-columns:5.5rem minmax(0,1fr) 4rem 3.5rem}}.label{color:var(${CHART_CHROME.tickColour});font-size:var(${CHART_CHROME.tickSize});white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.track{position:relative;height:10px;background:var(--bg);border-radius:2px}.axis{position:absolute;top:-2px;bottom:-2px;left:50%;border-left:1px solid var(--border-strong)}.ref{position:absolute;top:-3px;bottom:-3px;border-left:1px dashed var(--text-faint);z-index:1}.fill{position:absolute;top:0;bottom:0;border-radius:2px}.fill[data-tone='pos']{background:var(--pos)}.fill[data-tone='neg']{background:var(--neg)}.fill[data-tone='above']{background:var(--accent)}.fill[data-tone='below']{background:var(--text-faint)}.value{text-align:right;color:var(--text);white-space:nowrap}.n{text-align:right;color:var(--text-faint);font-size:var(--text-chip);white-space:nowrap}li.withheld .label,li.withheld .value{color:var(--text-faint)}`})
export class BarList {
 readonly rows=input.required<readonly BarRow[]>(); readonly mode=input<BarListMode>('signed'); readonly format=input.required<(value:number)=>string>(); readonly max=input<number|null>(null); readonly reference=input<number|null>(null); readonly withheldFloor=input<number|null>(null);
 private readonly ceiling=computed(()=>{const x=this.max();if(x!==null&&x>0)return x;const a=this.rows().map(r=>r.value).filter((v):v is number=>typeof v==='number'&&Number.isFinite(v)).map(Math.abs);return a.length?Math.max(...a)||1:1;});
 protected readonly drawn=computed<Drawn[]>(()=>this.rows().map(row=>{const v=row.value,usable=!row.withheld&&typeof v==='number'&&Number.isFinite(v),text=usable?this.format()(v):ABSENT;if(!usable||v===0)return {...row,text,left:0,width:0,tone:'pos' as Tone};if(this.mode()==='rate'){const width=this.clamp(v),ref=this.reference();return {...row,text,left:0,width,tone:(ref===null||v>=ref?'above':'below')as Tone};}const half=Math.min(50,Math.abs(v)/this.ceiling()*50);return v>0?{...row,text,left:50,width:half,tone:'pos'as Tone}:{...row,text,left:50-half,width:half,tone:'neg'as Tone};}));
 protected clamp(value:number){return Math.min(100,Math.max(0,value));} protected nText(row:Drawn){if(row.n===null||row.n===undefined)return '';const floor=this.withheldFloor();return row.withheld&&floor!==null?`n=${row.n} · <${floor}`:`n=${row.n}`;}
}
