import { Component, provideZonelessChangeDetection, signal } from '@angular/core'; import { TestBed } from '@angular/core/testing'; import { beforeEach, describe, expect, it } from 'vitest';
import { Figure, FigureStrip, FigureTone } from './figure';
function figure(value: number | null, tone: FigureTone = 'plain', extra: { unit?: string; decimals?: number; sub?: string } = {}) { const f = TestBed.createComponent(Figure); f.componentRef.setInput('label', 'Expectancy'); f.componentRef.setInput('value', value); f.componentRef.setInput('tone', tone); for (const [key, input] of Object.entries(extra)) f.componentRef.setInput(key, input); f.detectChanges(); return f.nativeElement as HTMLElement; }
@Component({ imports: [Figure, FigureStrip], template: `<sb-figure-strip>@for (n of figures(); track n) { <sb-figure [label]="'F' + n" [value]="n" /> }</sb-figure-strip>` }) class StripHost { readonly figures = signal([1, 2, 3]); }
describe('Figure (v80 D4)', () => { beforeEach(() => TestBed.configureTestingModule({ providers: [provideZonelessChangeDetection()] })); const value = (e: HTMLElement) => e.querySelector('.value')!;
  it('labels and formats with unit', () => { const e = figure(54.23, 'plain', { unit: '%', decimals: 1 }); expect(e.querySelector('.sb-label')!.textContent!.trim()).toBe('Expectancy'); expect(value(e).textContent!.trim()).toBe('54.2%'); });
  it('colours P&L by sign but not zero/plain', () => { expect(value(figure(.21, 'pnl')).classList).toContain('pos'); expect(value(figure(-.4, 'pnl')).classList).toContain('neg'); expect(value(figure(0, 'pnl')).className).not.toMatch(/pos|neg/); expect(value(figure(-3)).className).not.toMatch(/pos|neg/); });
  it('uses caution and absent states', () => { expect(value(figure(82, 'caution')).classList).toContain('warn'); expect(value(figure(null, 'pnl', { unit: '%' })).textContent!.trim()).toBe('—'); });
  it('shows optional subline', () => { expect(figure(1, 'plain', { sub: 'n = 184' }).querySelector('.sub')!.textContent!.trim()).toBe('n = 184'); }); });
describe('FigureStrip (v80 D4)', () => { beforeEach(() => TestBed.configureTestingModule({ providers: [provideZonelessChangeDetection()] })); it('sets up to four columns', () => { const f = TestBed.createComponent(StripHost); f.detectChanges(); const strip = (f.nativeElement as HTMLElement).querySelector('sb-figure-strip') as HTMLElement; expect(strip.style.getPropertyValue('--figure-columns')).toBe('3'); f.componentInstance.figures.set([1,2,3,4,5]); f.detectChanges(); expect(strip.style.getPropertyValue('--figure-columns')).toBe('4'); }); });
