import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core';
import { CHART_CHROME } from './chart/chart-frame';
import { ChartTooltip, HoverState, hoverPosition } from './chart-tooltip';
export interface WaterfallStep { label: string; value: number; n?: number; }
const W = 320, ROW = 22, LABEL_W = 96, PAD = 8;
@Component({ selector: 'sb-waterfall', changeDetection: ChangeDetectionStrategy.OnPush, imports: [ChartTooltip], template: `<div class="host" #host><svg [attr.viewBox]="'0 0 ' + width + ' ' + height()" [attr.height]="height()" width="100%" role="img" aria-label="Contribution waterfall"><line class="zero" [attr.x1]="x(0)" [attr.x2]="x(0)" y1="0" [attr.y2]="height()" />@for (row of rows(); track row.label; let i = $index) { <text class="label" [attr.x]="labelW - 6" [attr.y]="i * rowH + rowH / 2 + 4" text-anchor="end">{{ row.label }}</text><rect class="bar" rx="4" [attr.data-tone]="row.tone" [attr.x]="row.x" [attr.y]="i * rowH + 5" [attr.width]="row.w" height="12" tabindex="0" (pointermove)="show($event,row,host)" (focus)="show($event,row,host)" (pointerleave)="hover.set(null)" (blur)="hover.set(null)"/><text class="value num" [attr.x]="row.tx" [attr.y]="i * rowH + rowH / 2 + 4" [attr.text-anchor]="row.anchor">{{ format()(row.value) }}</text> }</svg><sb-chart-tooltip [state]="hover()" [hostWidth]="host.clientWidth" /></div>`, styles: `.host { position:relative; } svg { display:block; overflow:visible; } .zero { stroke:var(${CHART_CHROME.axis}); stroke-width:1; } .bar[data-tone='pos'] { fill:var(--pos); } .bar[data-tone='neg'] { fill:var(--neg); } .bar[data-tone='total'] { fill:var(--accent); } .label { fill:var(${CHART_CHROME.tickColour}); font-size:11px; } .value { fill:var(--text); font-size:11px; }` })
export class Waterfall {
  readonly steps = input.required<readonly WaterfallStep[]>(); readonly format = input<(v: number) => string>((v) => v.toFixed(2)); readonly totalLabel = input('Total'); protected readonly width = W; protected readonly rowH = ROW; protected readonly labelW = LABEL_W; protected readonly hover = signal<HoverState | null>(null);
  protected readonly runs = computed<[number, number][]>(() => { let run = 0; const output: [number, number][] = []; for (const step of this.steps()) { output.push([run, run + step.value]); run += step.value; } output.push([0, run]); return output; });
  private readonly domain = computed(() => { const values = this.runs().flat(); return { min: Math.min(0, ...values), max: Math.max(0, ...values) }; }); protected readonly height = computed(() => (this.steps().length + 1) * ROW);
  protected x(value: number): number { const { min, max } = this.domain(); return LABEL_W + PAD + (value - min) / (max - min || 1) * (W - LABEL_W - 2 * PAD); }
  protected readonly rows = computed(() => { const steps = [...this.steps(), { label: this.totalLabel(), value: this.runs().at(-1)![1] }]; return steps.map((step, index) => { const [a, b] = this.runs()[index]; const x0 = this.x(Math.min(a, b)), x1 = this.x(Math.max(a, b)), right = b >= a; return { label: step.label, value: index === steps.length - 1 ? b : step.value, n: (step as WaterfallStep).n, tone: index === steps.length - 1 ? 'total' : step.value >= 0 ? 'pos' : 'neg', x: x0, w: Math.max(2, x1 - x0), tx: right ? x1 + 4 : x0 - 4, anchor: right ? 'start' : 'end' }; }); });
  protected show(event: PointerEvent | FocusEvent, row: { label: string; value: number; n?: number }, host: HTMLElement): void { this.hover.set({ ...hoverPosition(event, host), title: row.label, rows: [{ label: 'contribution', value: this.format()(row.value) }, ...(row.n == null ? [] : [{ label: 'trades', value: String(row.n) }])] }); }
}
