#!/bin/sh
# Claude Code statusline: profile, model, cwd, git branch/dirty count,
# context %, session (5h) usage %, weekly (7d) usage %, and their reset
# times — each with an icon + color.
#
# Session/weekly usage comes straight off the live statusLine JSON payload
# (rate_limits.five_hour / .seven_day), which Claude Code refreshes on every
# render for THIS process's own authenticated account — NOT from the
# cachedUsageUtilization blob in <config>/.claude.json, which only updates
# when something (e.g. /usage) explicitly refetches it and can sit stale for
# many minutes. That distinction matters most when several accounts/profiles
# run concurrently: the live payload can never leak another profile's
# numbers in, since it's generated by this exact process for its own
# account, whereas a shared/stale cache file read by config-dir path is only
# as good as which profile last happened to refresh it.

script_dir=$(dirname "$0")
input=$(cat)

RESET='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'
MAGENTA='\033[35m'
CYAN='\033[36m'
BLUE='\033[34m'
GREEN='\033[32m'
YELLOW='\033[33m'
RED='\033[31m'
GRAY='\033[90m'

# --- gather values: one python pass over the live JSON payload ---
fields=$(printf '%s' "$input" | python "$script_dir/statusline_fields.py" 2>/dev/null)
IFS='	' read -r model ctx_raw sess sess_reset_epoch week week_reset_epoch <<EOF
$fields
EOF

branch=$(git --no-optional-locks rev-parse --abbrev-ref HEAD 2>/dev/null)
dirty=$(git --no-optional-locks status --porcelain 2>/dev/null | wc -l | tr -d ' ')
dir=$(basename "$PWD")

cfgdir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
profile=$(printf '%s' "$cfgdir" | sed 's#.*[\\/]##')
profile=${profile#config-}
[ -n "$profile" ] && profile="claude-$profile"

sess_reset=""
[ -n "$sess_reset_epoch" ] && sess_reset=$(date -d "@$sess_reset_epoch" +"%H:%M" 2>/dev/null)
week_reset=""
[ -n "$week_reset_epoch" ] && week_reset=$(date -d "@$week_reset_epoch" +"%a %H:%M" 2>/dev/null)

# fallback for older Claude Code builds whose statusLine payload has no
# rate_limits block yet: fall back to this SAME profile's own cached usage
# snapshot (<config-dir>/.claude.json), flagged with its age since that path
# really can be stale. Still scoped to $cfgdir, so it cannot cross accounts.
cache_kind_pct=""
cache_kind_reset=""
read_cache_kind() {
  kind="$1"
  cfgfile="$cfgdir/.claude.json"
  cache_kind_pct=""
  cache_kind_reset=""
  [ -f "$cfgfile" ] || return
  flat=$(tr -d '\n' < "$cfgfile")
  block=$(printf '%s' "$flat" | grep -o "\"kind\": \"$kind\"[^}]*}" | head -1)
  cache_kind_pct=$(printf '%s' "$block" | sed -n 's/.*"percent": *\([0-9]*\).*/\1/p')
  reset_raw=$(printf '%s' "$block" | sed -n 's/.*"resets_at": *"\([^"]*\)".*/\1/p')
  [ -n "$reset_raw" ] && cache_kind_reset=$(date -d "$reset_raw" +"$2" 2>/dev/null)
}

age_min=""
if [ -z "$sess" ]; then
  read_cache_kind "session" "%H:%M"
  sess="$cache_kind_pct"
  sess_reset="$cache_kind_reset"

  cfgfile="$cfgdir/.claude.json"
  if [ -f "$cfgfile" ]; then
    fetched_ms=$(tr -d '\n' < "$cfgfile" | sed -n 's/.*"fetchedAtMs": *\([0-9]*\).*/\1/p' | head -1)
    if [ -n "$fetched_ms" ]; then
      now_ms=$(date +%s%3N)
      age_min=$(awk -v now="$now_ms" -v fetched="$fetched_ms" 'BEGIN { printf "%.0f", (now - fetched) / 60000 }' 2>/dev/null)
    fi
  fi
fi
if [ -z "$week" ]; then
  read_cache_kind "weekly_all" "%a %H:%M"
  week="$cache_kind_pct"
  week_reset="$cache_kind_reset"
fi

# round context % to 1 decimal place
ctx=""
[ -n "$ctx_raw" ] && ctx=$(printf '%.1f' "$ctx_raw" 2>/dev/null)

# --- color grading for percentages: green < 50, yellow < 80, red >= 80 ---
pct_color() {
  v=$(printf '%.0f' "$1" 2>/dev/null)
  [ -z "$v" ] && v=0
  if [ "$v" -ge 80 ]; then printf '%s' "$RED"
  elif [ "$v" -ge 50 ]; then printf '%s' "$YELLOW"
  else printf '%s' "$GREEN"
  fi
}

SEP="${DIM} |${RESET}"
out=""

if [ -n "$profile" ]; then
  out="${BOLD}${MAGENTA}\xf0\x9f\x91\xa4 ${profile}${RESET}"
fi

if [ -n "$model" ]; then
  seg="${CYAN}\xf0\x9f\xa4\x96 ${model}${RESET}"
  out="${out}${out:+ $SEP }${seg}"
fi

seg="${BLUE}\xf0\x9f\x93\x81 ${dir}${RESET}"
out="${out}${out:+ $SEP }${seg}"

if [ -n "$branch" ]; then
  seg="${GREEN}\xf0\x9f\x8c\xbf ${branch}${RESET}"
  out="${out}${out:+ $SEP }${seg}"
fi

if [ -n "$dirty" ] && [ "$dirty" != "0" ]; then
  seg="${YELLOW}\xe2\x9c\x8e +${dirty}${RESET}"
  out="${out}${out:+ $SEP }${seg}"
fi

if [ -n "$ctx" ]; then
  c=$(pct_color "$ctx")
  seg="${c}\xf0\x9f\x93\x8a ctx ${ctx}%${RESET}"
  out="${out}${out:+ $SEP }${seg}"
fi

if [ -n "$sess" ]; then
  c=$(pct_color "$sess")
  age_note=""
  if [ -n "$age_min" ]; then
    if [ "$age_min" -ge 10 ]; then
      c="$GRAY"
      age_note=" (${age_min}m stale)"
    elif [ "$age_min" -ge 1 ]; then
      age_note=" (${age_min}m ago)"
    fi
  fi
  reset_note=""
  [ -n "$sess_reset" ] && reset_note=" \xe2\x86\xbb ${sess_reset}"
  seg="${c}\xe2\x8f\xb3 sess ${sess}%${age_note}${reset_note}${RESET}"
  out="${out}${out:+ $SEP }${seg}"
fi

if [ -n "$week" ]; then
  c=$(pct_color "$week")
  reset_note=""
  [ -n "$week_reset" ] && reset_note=" \xe2\x86\xbb ${week_reset}"
  seg="${c}\xf0\x9f\x93\x85 wk ${week}%${reset_note}${RESET}"
  out="${out}${out:+ $SEP }${seg}"
fi

printf "%b" "$out"
