"""Prove a running instance actually serves a working SPA.

Run against a container, a staging box, or production:

    python scripts/smoke_spa.py --url http://localhost:1234 --user ci --password ci-secret
    python scripts/smoke_spa.py --url https://admin.example.com --user admin --password "$PW"

**Why this exists.** NG54's acceptance walk found the SPA served a black
screen: the build stamped `<base href="/">` while Flask serves the bundle from
`/app/`, so every asset 404ed. 1537 Python tests and 294 Angular tests were
green over it. They could not have caught it -- the Python tests write a *fake*
index.html into `static/app/`, and the Angular tests never load one. Neither
suite has ever seen the artifact that actually ships.

That is the gap this closes, and it is a permanent one rather than a one-off:
`static/app/` is gitignored and produced only by the Dockerfile's frontend
stage, so **the thing CI validates is never the thing that deploys** unless
something fetches the real page over HTTP and follows what it asks for.

So this does exactly that, and deliberately no more:

  1. `/api/v1/health` answers.
  2. The front door behaves as the ADMIN_UI flag says it should.
  3. The SPA's index.html loads and contains the app's root element.
  4. **Every asset that index.html references resolves to a 200** -- resolved
     through its own `<base href>`, which is the specific thing that broke.
  5. Each workspace route serves the shell rather than 404ing.

Stdlib only: it runs inside a slim container and in CI with nothing installed.
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request

#: Matches src="..." / href="..." on script and link tags. Deliberately a
#: regex rather than an HTML parser: the file is machine-generated by the
#: Angular builder, and the alternative is a dependency in a slim image.
_ASSET_RE = re.compile(
    r'<(?:script|link)\b[^>]*?\b(?:src|href)=["\']([^"\']+)["\']',
    re.IGNORECASE,
)

#: Workspaces, from spa.py's WORKSPACES. Keep the two lists in step: this one
#: went stale the moment SR4/SR5 renamed Cockpit to Dashboard and Universe to
#: Watchlist, and because the old names still serve (as redirect targets) the
#: check kept passing while testing neither new route. A verification that
#: silently stops covering the thing that changed is worse than none.
#:
#: `/risk` is absent on purpose: until NG57 deletes the Jinja routes, a hard
#: GET of it lands on the Jinja page by design (see spa.py:register).
#: Asserting it serves the SPA would fail on a correct deployment.
WORKSPACES = ("dashboard", "trades", "analytics", "watchlist", "system")

#: The pre-SR4/SR5 URLs, kept server-side so a bookmark or an open tab does
#: not 404 before Angular loads and can redirect it. Checked because losing
#: them breaks quietly -- the person affected is the one who bookmarked a page
#: months ago, and they see a 404 with no way to know it used to work.
LEGACY_WORKSPACES = ("cockpit", "universe")

#: Assets that are allowed to be missing. Angular emits a favicon link whether
#: or not one was provided, and a missing favicon is not a broken deployment.
_OPTIONAL = ("favicon.ico",)


class Smoke:
    def __init__(self, base: str, user: str | None, password: str | None,
                 timeout: float):
        self.base = base.rstrip("/")
        self.timeout = timeout
        self.auth = None
        if user is not None and password is not None:
            token = base64.b64encode(f"{user}:{password}".encode()).decode()
            self.auth = f"Basic {token}"
        self.failures: list[str] = []
        self.checks = 0

    # -- plumbing ---------------------------------------------------------

    def get(self, path: str, *, follow: bool = True):
        """Return (status, body, headers). Never raises for an HTTP status."""
        url = path if path.startswith("http") else f"{self.base}{path}"
        request = urllib.request.Request(url)
        if self.auth:
            request.add_header("Authorization", self.auth)

        opener = urllib.request.build_opener()
        if not follow:
            opener = urllib.request.build_opener(_NoRedirect)
        try:
            with opener.open(request, timeout=self.timeout) as response:
                return response.status, response.read(), dict(response.headers)
        except urllib.error.HTTPError as exc:
            return exc.code, exc.read(), dict(exc.headers)
        except urllib.error.URLError as exc:
            return 0, str(exc.reason).encode(), {}
        except OSError as exc:
            # RemoteDisconnected and friends are ConnectionError -> OSError,
            # NOT URLError, so they escape the clause above and surface as a
            # traceback. That happens routinely when this runs against a
            # container that is still binding its port, and a traceback there
            # reads like a broken script rather than "not up yet".
            return 0, f"{type(exc).__name__}: {exc}".encode(), {}

    def check(self, ok: bool, label: str, detail: str = "") -> bool:
        self.checks += 1
        if ok:
            print(f"  ok    {label}")
        else:
            print(f"  FAIL  {label}" + (f"  -- {detail}" if detail else ""))
            self.failures.append(label)
        return ok

    # -- the checks -------------------------------------------------------

    def health(self) -> None:
        status, body, _ = self.get("/api/v1/health")
        detail = f"HTTP {status}"
        if status == 401:
            # Worth naming, because every later check fails the same way and
            # the result looks like a broken UI rather than a wrong password.
            detail += (" -- credentials rejected. Check ADMIN_USERNAME /"
                       " ADMIN_PASSWORD, including a trailing \r from a"
                       " CRLF .env.")
        if not self.check(status == 200, "GET /api/v1/health", detail):
            return
        try:
            json.loads(body)
        except ValueError:
            self.check(False, "health returns JSON", body[:80].decode("utf-8", "replace"))

    def front_door(self, expect_spa: bool) -> None:
        """`/` with ADMIN_UI=spa redirects to /cockpit; with jinja it renders.

        Checked without following the redirect, because *which* it does is the
        whole meaning of the flag -- a followed redirect makes both modes look
        identical.
        """
        status, _, headers = self.get("/", follow=False)
        location = headers.get("Location", "")
        if expect_spa:
            # Assert the PROPERTY, not the destination: the front door
            # redirects, and wherever it points serves the app. Hardcoding
            # "/cockpit" here went stale the day SR4 renamed it to
            # "/dashboard" -- the app was right and the check was wrong, which
            # is the failure mode that teaches people to ignore the check.
            redirected = status in (301, 302, 303, 307, 308)
            if not self.check(redirected, "GET / redirects (ADMIN_UI=spa)",
                              f"HTTP {status} Location={location!r}"):
                return
            target_status, target_body, _ = self.get(location)
            self.check(
                target_status == 200 and b"<sb-root>" in target_body,
                f"GET / lands on {location} and it serves the app",
                f"HTTP {target_status}",
            )
        else:
            self.check(status == 200, "GET / renders (ADMIN_UI=jinja)", f"HTTP {status}")

    def index_and_assets(self) -> None:
        """The check that would have caught NG54's blocker."""
        status, body, _ = self.get("/cockpit")
        if not self.check(status == 200, "GET /cockpit", f"HTTP {status}"):
            return
        html = body.decode("utf-8", "replace")

        if not self.check("<sb-root>" in html, "index.html carries <sb-root>"):
            return

        base_match = re.search(r'<base\s+href=["\']([^"\']+)["\']', html, re.I)
        base_href = base_match.group(1) if base_match else "/"
        print(f"        <base href=\"{base_href}\">")

        assets = [a for a in _ASSET_RE.findall(html)
                  if not a.startswith(("http://", "https://", "data:"))]
        if not self.check(bool(assets), "index.html references at least one asset"):
            return

        for asset in assets:
            # The browser resolves a relative URL against <base href>. Doing
            # the same here is the point: it is the step that disagreed with
            # where Flask serves the bundle.
            resolved = urllib.parse.urljoin(base_href, asset)
            status, _, _ = self.get(resolved)
            optional = any(asset.endswith(o) for o in _OPTIONAL)
            if status == 200 or (optional and status == 404):
                suffix = "  (optional, absent)" if status == 404 else ""
                self.check(True, f"asset {resolved}{suffix}")
            else:
                self.check(
                    False, f"asset {resolved}",
                    f"HTTP {status} -- index.html asks for a path the server "
                    f"does not serve. This is the base-href mismatch: check "
                    f"angular.json's baseHref against spa.py's asset route.",
                )

    def workspaces(self) -> None:
        for workspace in WORKSPACES:
            status, body, _ = self.get(f"/{workspace}")
            self.check(
                status == 200 and b"<sb-root>" in body,
                f"GET /{workspace} serves the SPA shell",
                f"HTTP {status}",
            )
        for workspace in LEGACY_WORKSPACES:
            status, body, _ = self.get(f"/{workspace}")
            self.check(
                status == 200 and b"<sb-root>" in body,
                f"GET /{workspace} still resolves (old bookmarks)",
                f"HTTP {status} -- dropping it 404s a bookmark before Angular "
                f"can redirect it",
            )

    # -- runner -----------------------------------------------------------

    def run(self, expect_spa: bool) -> int:
        print(f"Smoke-testing {self.base}\n")
        self.health()
        self.front_door(expect_spa)
        if expect_spa:
            self.index_and_assets()
            self.workspaces()

        print()
        if self.failures:
            print(f"FAILED: {len(self.failures)} of {self.checks} checks")
            for name in self.failures:
                print(f"  - {name}")
            return 1
        print(f"PASS: {self.checks} checks")
        return 0


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *_args, **_kwargs):
        return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--url", default="http://localhost:1234",
                        help="Base URL of the running admin UI.")
    parser.add_argument("--user", help="Basic-auth username.")
    parser.add_argument("--password", help="Basic-auth password.")
    parser.add_argument(
        "--from-config", action="store_true",
        help="Read credentials and the expected UI from swingbot.config "
             "instead of the command line. Only valid when running inside "
             "the app's own container.",
    )
    parser.add_argument("--timeout", type=float, default=10.0)
    parser.add_argument(
        "--expect", choices=("spa", "jinja"), default="spa",
        help="Which UI the instance is configured to serve at /. Default spa.",
    )
    args = parser.parse_args(argv)

    user, password, expect = args.user, args.password, args.expect
    if args.from_config:
        # Read what the SERVER reads, from the same parser, in the same
        # process space. The alternative -- sourcing .env in bash and passing
        # the values in -- looks equivalent and is not: `.` runs the file
        # through the shell, so a password containing `$`, a backtick or `!`
        # is expanded or mangled on the way, and a .env written on Windows
        # adds a trailing CR to every value. Both produce a 401 for a password
        # that is perfectly correct in the file, and both bit this script on
        # a real deploy before it read the config directly.
        import sys as _sys
        _sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        from swingbot import config

        user = getattr(config, "ADMIN_USERNAME", None) or user
        password = getattr(config, "ADMIN_PASSWORD", None) or password
        expect = getattr(config, "ADMIN_UI", None) or expect
        if "--url" not in (argv if argv is not None else sys.argv[1:]):
            # 127.0.0.1, not localhost: inside the container `localhost` can
            # resolve to ::1 first while Flask binds IPv4, which failed on one
            # container and succeeded on another from the same image.
            port = getattr(config, "ADMIN_PORT", None) or 1234
            args.url = f"http://127.0.0.1:{port}"

    smoke = Smoke(args.url, user, password, args.timeout)
    return smoke.run(expect_spa=expect == "spa")


if __name__ == "__main__":
    raise SystemExit(main())
