"""Econ event calendar. Event = {date, time_et, kind, label, importance}.
History is generated by scripts/build_event_history.py; the future edge
is kept fresh by refresh_future_events (G30)."""
from __future__ import annotations

import datetime as dt
import os
from zoneinfo import ZoneInfo

from swingbot import config
from swingbot.core.jsonio import atomic_write_json, read_json

ET = ZoneInfo("America/New_York")

KINDS = ("fomc", "cpi", "ppi", "nfp", "pce", "opex", "holiday")
IMPORTANCE = {"fomc": 3, "cpi": 3, "nfp": 3, "ppi": 2, "pce": 2, "opex": 1, "holiday": 1}
EVENTS_PATH = os.path.join(config.DATA_DIR, "macro", "event_history.json")


def load_events(path: str | None = None) -> list[dict]:
    rows = read_json(path or EVENTS_PATH, default=[]) or []
    out = []
    for e in rows:
        try:
            importance = int(e.get("importance", 0))
        except (TypeError, ValueError):
            continue
        if e.get("kind") in KINDS and e.get("date") and 1 <= importance <= 3:
            out.append(e)
    return sorted(out, key=lambda e: (e["date"], e["kind"]))


def events_between(start: str, end: str, events: list[dict] | None = None) -> list[dict]:
    events = load_events() if events is None else events
    return [e for e in events if start <= e["date"] <= end]   # both bounds inclusive


def events_on(date: str, events: list[dict] | None = None) -> list[dict]:
    return events_between(date, date, events)


# Future FOMC decision days beyond what's in event_history.json — update
# when the Fed publishes next year's calendar (same source URL as
# scripts/build_event_history.py). The shipped history already runs through
# 2026-12-09, so this stays empty until the 2027 calendar is published.
FUTURE_FOMC: list[str] = []

_RELEASES = {"cpi": 10, "ppi": 46, "nfp": 50, "pce": 54}


def refresh_future_events(days_ahead: int = 45, today: dt.date | None = None) -> int:
    """Merge newly published release dates + FUTURE_FOMC into the events
    file. Idempotent by (date, kind). Returns rows added. Called by the
    snapshot scheduler (G39) at most daily."""
    from swingbot.core.macro import fred as fred_mod

    today = today or dt.date.today()
    horizon = (today + dt.timedelta(days=days_ahead)).isoformat()
    start = today.isoformat()
    existing = load_events()
    seen = {(e["date"], e["kind"]) for e in existing}
    added = []

    def _add(date, kind, time_et, label):
        if start <= date <= horizon and (date, kind) not in seen:
            added.append({"date": date, "time_et": time_et, "kind": kind,
                          "label": label, "importance": IMPORTANCE[kind]})
            seen.add((date, kind))

    for kind, release_id in _RELEASES.items():
        for date in fred_mod.fred_release_dates(release_id, include_future=True):
            _add(date, kind, "08:30", f"{kind.upper()} release")
    for date in FUTURE_FOMC:
        _add(date, "fomc", "14:00", "FOMC decision")
    if added:
        merged = sorted(existing + added, key=lambda e: (e["date"], e["kind"]))
        atomic_write_json(EVENTS_PATH, merged)
    return len(added)


def _event_dt_utc(event: dict) -> dt.datetime:
    hh, mm = (int(x) for x in (event.get("time_et") or "09:30").split(":"))
    d = dt.date.fromisoformat(event["date"])
    naive_et = dt.datetime(d.year, d.month, d.day, hh, mm, tzinfo=ET)
    return naive_et.astimezone(dt.timezone.utc)


def next_event(kinds=None, now: dt.datetime | None = None,
               events: list[dict] | None = None) -> dict | None:
    now = now or dt.datetime.now(dt.timezone.utc)
    for e in (load_events() if events is None else events):
        if kinds and e["kind"] not in kinds:
            continue
        if _event_dt_utc(e) >= now:
            return e
    return None


def hours_until(event: dict, now: dt.datetime | None = None) -> float:
    now = now or dt.datetime.now(dt.timezone.utc)
    return (_event_dt_utc(event) - now).total_seconds() / 3600.0
